Bugfixes for CI jobs

diff --git a/cli/.circleci/config.yml b/cli/.circleci/config.yml
--- a/cli/.circleci/config.yml
+++ b/cli/.circleci/config.yml
@@ -222,8 +222,8 @@ jobs:
           echo 'export KURTOSIS_BINPATH="<< pipeline.parameters.workspace-with-cli-binary-mountpoint >>/<< pipeline.parameters.cli-dist-home-relative-dirpath >>/<< pipeline.parameters.cli-linux-amd-64-binary-relative-filepath >>"' >> "${BASH_ENV}"
       - run: |
           function test_config_init_is_required() {
-            if ${KURTOSIS_BINPATH} engine status; then
-              echo "Error: Expected an attempt to use the Kurtosis CLI in a non-interactive terminal without init'ing the config first to fail" >&2
+            if ${KURTOSIS_BINPATH} engine start; then
+              echo "Error: Expected an attempt to use the Kurtosis CLI in a non-interactive terminal without init'ing the config first to fail but it succeeded" >&2
               return 1
             fi
           }
