Guarantee we dump the enclaves after we run the testsuites

diff --git a/cli/.circleci/config.yml b/cli/.circleci/config.yml
--- a/cli/.circleci/config.yml
+++ b/cli/.circleci/config.yml
@@ -117,9 +117,14 @@ jobs:
       #We do not send metrics from CI to not dirty the metrics data
       - run: "${KURTOSIS_BINPATH} config init dont-send-metrics"
       - run: "${KURTOSIS_BINPATH} engine start"
-      - run: ./internal_testsuites/golang/scripts/build.sh
 
-      # Package the logs so we can debug any issues that arise
+      # Run the testsuite, but don't fail the job immediately so that we can upload the enclave dump
+      - run: |
+          if ! ./internal_testsuites/golang/scripts/build.sh; then
+            touch /tmp/testsuite-failed
+          fi
+
+      # Dump enclave data so we can debug any issues that arise
       - run: |
           set -euo pipefail
           cd /tmp
@@ -133,6 +138,9 @@ jobs:
           path: /tmp/enclave-dumps.zip
           destination: golang-testsuite-enclaves.zip
 
+      # Finally, fail the job if the testsuite failed
+      - run: ! [ -f /tmp/testsuite-failed ]
+
   build_typescript_testsuite:
     executor: ubuntu_vm
     steps:
@@ -144,17 +152,25 @@ jobs:
           set -euo pipefail
           echo 'export KURTOSIS_BINPATH="<< pipeline.parameters.workspace-with-cli-binary-mountpoint >>/<< pipeline.parameters.cli-dist-home-relative-dirpath >>/<< pipeline.parameters.cli-linux-amd-64-binary-relative-filepath >>"' >> "${BASH_ENV}"
       - run: echo "${DOCKER_PASSWORD}" | docker login -u ${DOCKER_USERNAME} --password-stdin
+
+      #Run install Yarn because TypeScript tests are managed with Yarn package manager
+      - run: npm install -g yarn
+
       #Run config init to avoid metrics consent prompt when execute engine start command,
       #We do not send metrics from CI to not dirty the metrics data
       - run: "${KURTOSIS_BINPATH} config init dont-send-metrics"
       - run: "${KURTOSIS_BINPATH} engine start"
-      #Run install Yarn because TypeScript tests are managed with Yarn package manager
-      - run: npm install -g yarn
-      - run: ./internal_testsuites/typescript/scripts/build.sh
 
-      # Package the logs so we can debug any issues that arise
+      # Run the testsuite, but don't fail the job immediately so that we can upload the enclave dump
+      - run: |
+          if ! ./internal_testsuites/typescript/scripts/build.sh; then
+            touch /tmp/testsuite-failed
+          fi
+
+      # Dump enclave data so we can debug any issues that arise
       - run: |
           set -euo pipefail
+          ./internal_testsuites/typescript/scripts/build.sh
           cd /tmp
           output_dirname="enclave-dumps"
           mkdir "${output_dirname}"
@@ -165,6 +181,9 @@ jobs:
       - store_artifacts:
           path: /tmp/enclave-dumps.zip
           destination: typescript-testsuite-enclaves.zip
+
+      # Finally, fail the job if the testsuite failed
+      - run: ! [ -f /tmp/testsuite-failed ]
   # -- End build jobs ---------------------------------------
 
   # -- Artifact-publishing jobs --------------------------------
